### ISSUE TITLE
在运行到parseRawData()时出现PACKET_SIZE doesn't match的情况请问是怎么回事？代码给出的PACKET_SIZE 是1240， 而pandar128发送过来的是数据长度是861

### ISSUE THREAD

**Issue by li-mandy** [HesaiTechnology/HesaiLidar_Pandar128_ROS#9]

**Comment by yangfanFred** [comment]
Hi Mandy,

parseRawData()函数属于历史版本遗留代码，数据结构不对应Pandar128的，现在版本中这个函数不应该起作用；
请问您是如何操作运行到这个函数的？是否更改了原始代码？

Thanks,
Fred

**Comment by li-mandy** [comment]
> Hi Mandy,
> 
> parseRawData()函数属于历史版本遗留代码，数据结构不对应Pandar128的，现在版本中这个函数不应该起作用； 请问您是如何操作运行到这个函数的？是否更改了原始代码？
> 
> Thanks, Fred

**Comment by li-mandy** [comment]
感谢回复，问题已解决
